
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Thu Apr 15 01:49:00 CEST 2021
//----------------------------------------------------

package asintAsc;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int r_true = 44;
  public static final int amp = 11;
  public static final int call = 38;
  public static final int r_null = 46;
  public static final int llcierre = 23;
  public static final int mod = 49;
  public static final int flecha = 59;
  public static final int r_false = 45;
  public static final int array = 16;
  public static final int r_real = 12;
  public static final int write = 34;
  public static final int blt = 55;
  public static final int ent = 19;
  public static final int pap = 8;
  public static final int r_else = 28;
  public static final int coma = 10;
  public static final int igual = 25;
  public static final int real = 42;
  public static final int ble = 52;
  public static final int pointer = 24;
  public static final int scol = 3;
  public static final int read = 33;
  public static final int r_string = 15;
  public static final int endwhile = 32;
  public static final int menos = 40;
  public static final int then = 27;
  public static final int r_if = 26;
  public static final int var = 4;
  public static final int EOF = 0;
  public static final int beq = 51;
  public static final int mas = 39;
  public static final int proc = 7;
  public static final int r_int = 13;
  public static final int error = 1;
  public static final int or = 57;
  public static final int endif = 29;
  public static final int por = 47;
  public static final int ccierre = 18;
  public static final int punto = 58;
  public static final int pcierre = 9;
  public static final int id = 5;
  public static final int bne = 50;
  public static final int delete = 37;
  public static final int of = 20;
  public static final int cap = 17;
  public static final int record = 21;
  public static final int and = 56;
  public static final int bgt = 54;
  public static final int not = 41;
  public static final int r_new = 36;
  public static final int r_bool = 14;
  public static final int div = 48;
  public static final int sep_di = 2;
  public static final int nl = 35;
  public static final int bge = 53;
  public static final int r_while = 30;
  public static final int cadena = 43;
  public static final int llap = 22;
  public static final int r_do = 31;
  public static final int type = 6;
}

