
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Fri May 21 15:45:52 CEST 2021
//----------------------------------------------------

package c_ast_ascendente;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int r_true = 40;
  public static final int amp = 10;
  public static final int call = 36;
  public static final int r_null = 42;
  public static final int llcierre = 21;
  public static final int mod = 45;
  public static final int flecha = 55;
  public static final int r_false = 41;
  public static final int array = 15;
  public static final int r_real = 11;
  public static final int write = 32;
  public static final int ent = 59;
  public static final int blt = 51;
  public static final int pap = 7;
  public static final int r_else = 26;
  public static final int coma = 9;
  public static final int igual = 23;
  public static final int real = 56;
  public static final int ble = 48;
  public static final int pointer = 22;
  public static final int scol = 3;
  public static final int read = 31;
  public static final int r_string = 14;
  public static final int endwhile = 30;
  public static final int menos = 38;
  public static final int then = 25;
  public static final int r_if = 24;
  public static final int var = 4;
  public static final int EOF = 0;
  public static final int beq = 47;
  public static final int mas = 37;
  public static final int proc = 6;
  public static final int r_int = 12;
  public static final int error = 1;
  public static final int or = 53;
  public static final int endif = 27;
  public static final int por = 43;
  public static final int ccierre = 17;
  public static final int punto = 54;
  public static final int pcierre = 8;
  public static final int id = 58;
  public static final int bne = 46;
  public static final int delete = 35;
  public static final int of = 18;
  public static final int cap = 16;
  public static final int record = 19;
  public static final int and = 52;
  public static final int bgt = 50;
  public static final int not = 39;
  public static final int r_new = 34;
  public static final int r_bool = 13;
  public static final int div = 44;
  public static final int sep_di = 2;
  public static final int nl = 33;
  public static final int bge = 49;
  public static final int r_while = 28;
  public static final int cadena = 57;
  public static final int llap = 20;
  public static final int r_do = 29;
  public static final int type = 5;
}

