/* Generated By:JavaCC: Do not edit this line. ConstructorASTConstants.java */
package c_ast_descendente;

public interface ConstructorASTConstants {

  int EOF = 0;
  int letra = 1;
  int digitoPositivo = 2;
  int digito = 3;
  int parteEntera = 4;
  int parteDecimal = 5;
  int parteExp = 6;
  int AllowedCharacters = 7;
  int var = 10;
  int type = 11;
  int proc = 12;
  int r_int = 13;
  int r_real = 14;
  int r_bool = 15;
  int r_string = 16;
  int array = 17;
  int of = 18;
  int record = 19;
  int pointer = 20;
  int r_if = 21;
  int then = 22;
  int endif = 23;
  int r_else = 24;
  int r_while = 25;
  int r_do = 26;
  int endwhile = 27;
  int read = 28;
  int write = 29;
  int nl = 30;
  int r_new = 31;
  int delete = 32;
  int call = 33;
  int not = 34;
  int r_true = 35;
  int r_false = 36;
  int r_null = 37;
  int and = 38;
  int or = 39;
  int punto = 40;
  int flecha = 41;
  int identificador = 42;
  int numeroEntero = 43;
  int numeroReal = 44;
  int str = 45;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<letra>",
    "<digitoPositivo>",
    "<digito>",
    "<parteEntera>",
    "<parteDecimal>",
    "<parteExp>",
    "<AllowedCharacters>",
    "<token of kind 8>",
    "<token of kind 9>",
    "\"var\"",
    "\"type\"",
    "\"proc\"",
    "\"int\"",
    "\"real\"",
    "\"bool\"",
    "\"string\"",
    "\"array\"",
    "\"of\"",
    "\"record\"",
    "\"pointer\"",
    "\"if\"",
    "\"then\"",
    "\"endif\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"endwhile\"",
    "\"read\"",
    "\"write\"",
    "\"nl\"",
    "\"new\"",
    "\"delete\"",
    "\"call\"",
    "\"not\"",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "\"and\"",
    "\"or\"",
    "\".\"",
    "\"->\"",
    "<identificador>",
    "<numeroEntero>",
    "<numeroReal>",
    "<str>",
    "\"&&\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"&\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"!=\"",
    "\"==\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"/\"",
    "\"%\"",
  };

}
